"""Installing themes from the bundled collection, a local path, a .zip, or a git remote.

A theme `source` can be:
  * a bare name already present in the bundled/installed collection (copied in),
  * a path to a theme directory (contains theme.toml) or a collection (themes/),
  * a .zip archive of a theme/collection (e.g. one produced by `gtheme export`),
  * a git URL or local git repo (cloned shallow, then its themes/ copied in).

Installed themes record where they came from in ``.gtheme-origin.json`` so
``update`` can refetch them. Git origins also record the resolved ``commit``
and the transport ``scheme``; path/zip/bundled origins record a content
``hash`` — both so ``update`` can tell whether anything changed. Zip installs
are recorded as type ``zip`` and treated as untrusted (they are the sharing
format), unlike plain local paths.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import re
import tempfile
import tomllib
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

from .. import ansi
from ..errors import GthemeError, ThemeSecurityError, ThemeValidationError
from ..paths import (
    BUNDLED_THEMES_DIR,
    INSTALLED_THEMES_DIR,
    ORIGIN_FILE,
    read_origin,
    safe_theme_name,
)
from ..validate import validate_dir

DEFAULT_REMOTE = "https://github.com/blyatiful1/gtheme"

# The community collection's registry (generated by `gtheme index`/`publish`).
INDEX_URL = "https://raw.githubusercontent.com/blyatiful1/gtheme/main/themes/index.json"

# How long (seconds) a single git network operation may take before we give up.
GIT_TIMEOUT = 120

# How long (seconds) an index fetch may take.
INDEX_TIMEOUT = 10


def fetch_index(timeout: float = INDEX_TIMEOUT) -> list[dict]:
    """Fetch the community collection's themes/index.json entries.

    Raises :class:`GthemeError` with a friendly message when offline or when
    the index is malformed — callers decide whether that is fatal.
    """
    try:
        with urllib.request.urlopen(INDEX_URL, timeout=timeout) as resp:  # noqa: S310 - fixed https URL
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        # Server answered: a 404 etc. is a publishing/URL problem, not connectivity.
        raise GthemeError(
            f"community index not available (HTTP {exc.code} {exc.reason})\n"
            f"  is the collection published at {INDEX_URL}?"
        )
    except (OSError, ValueError) as exc:  # URLError/timeout are OSErrors
        raise GthemeError(
            f"could not fetch the community theme index — are you online?\n"
            f"  ({INDEX_URL}: {getattr(exc, 'reason', exc)})"
        )
    entries = data.get("themes") if isinstance(data, dict) else None
    if not isinstance(entries, list):
        raise GthemeError(f"community index at {INDEX_URL} has an unexpected format")
    return [e for e in entries if isinstance(e, dict) and e.get("name")]

# scp-style git remote, e.g. git@github.com:user/repo.git
_SCP_RE = re.compile(r"^[\w.-]+@[\w.-]+:.+$")


def _is_url(s: str) -> bool:
    """True if ``s`` should be treated as a git URL rather than a local path.

    An existing local path always wins, so a real directory named ``foo.git``
    (or any path that exists on disk) is never force-routed to ``git clone``.
    """
    if Path(s).expanduser().exists():
        return False
    return "://" in s or s.endswith(".git") or s.startswith("git@")


def _scheme(s: str) -> str | None:
    """Return the URL scheme (lowercased) for ``s``, or None for local paths.

    scp-style ``git@host:path`` is reported as the synthetic scheme ``"scp"``.
    """
    m = re.match(r"^([A-Za-z][A-Za-z0-9+.-]*)://", s)
    if m:
        return m.group(1).lower()
    if _SCP_RE.match(s):
        return "scp"
    return None


def _check_scheme(source: str, *, insecure: bool) -> str:
    """Enforce the transport allowlist for ``source``; return its scheme.

    Allows https/ssh/scp-style and plain local paths unconditionally; allows
    file:// with a warning; rejects http:// and any other scheme unless
    ``insecure`` is set. Returns the scheme string ("local" for local paths).
    """
    scheme = _scheme(source)
    if scheme is None:
        return "local"
    if scheme in ("https", "ssh", "scp"):
        return scheme
    if scheme == "file":
        print(ansi.warn(f"file:// source is unverified: {source}"))
        return scheme
    if insecure:
        print(ansi.warn(f"allowing insecure transport '{scheme}://': {source}"))
        return scheme
    raise ThemeSecurityError(
        f"refusing insecure transport '{scheme}://' for {source}; "
        "use https/ssh, or pass --insecure to override"
    )


def _git_env() -> dict:
    # GIT_TERMINAL_PROMPT=0 so a missing/private repo fails fast instead of
    # blocking on an interactive credential prompt.
    return {**os.environ, "GIT_TERMINAL_PROMPT": "0"}


def _run_git(args: list[str], *, what: str) -> subprocess.CompletedProcess:
    """Run a git command, turning every failure into a clean GthemeError.

    Surfaces git's own stderr (repo-not-found, auth, host, no-space) instead of
    the opaque "exit status 128", and bounds network ops with a timeout so a
    stalled remote can't hang forever.
    """
    if shutil.which("git") is None:
        raise GthemeError("git is required for remote theme installs but was not found on PATH")
    try:
        return subprocess.run(
            ["git", *args],
            check=True, capture_output=True, text=True,
            env=_git_env(), timeout=GIT_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        raise GthemeError(f"git {what} timed out after {GIT_TIMEOUT}s (network stalled?)")
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or "").strip()
        raise GthemeError(f"git {what} failed:\n{detail}" if detail else f"git {what} failed (exit {exc.returncode})")
    except FileNotFoundError:
        raise GthemeError("git is required for remote theme installs but was not found on PATH")


def _git_clone(url: str, into: Path) -> tuple[Path, str]:
    """Shallow-clone ``url`` into ``into``; return (path, resolved commit hash)."""
    print(ansi.bullet(f"fetching {url} …"))
    # "--" terminates options so a URL like "-x.git" can't be read as a git flag.
    _run_git(["clone", "--depth", "1", "--", url, str(into)], what=f"clone {url}")
    rev = _run_git(["-C", str(into), "rev-parse", "HEAD"], what="rev-parse")
    return into, rev.stdout.strip()


def _remote_head(url: str) -> str | None:
    """Return the remote's HEAD commit via ls-remote, or None if undeterminable."""
    try:
        out = _run_git(["ls-remote", url, "HEAD"], what=f"ls-remote {url}").stdout.strip()
    except GthemeError:
        return None
    return out.split()[0] if out else None


def _force_rmtree(path: Path) -> None:
    """rmtree that also clears read-only modes so a protected dir can't strand us."""
    path = Path(path)
    if not (path.exists() or path.is_symlink()):
        return

    def _retry(func, p, _exc):
        try:
            os.chmod(p, 0o700)
            func(p)
        except OSError:
            pass

    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=lambda f, p, e: _retry(f, p, e))
    else:  # pragma: no cover - 3.11 fallback
        shutil.rmtree(path, onerror=lambda f, p, e: _retry(f, p, e))


def _copy_theme(src: Path, name: str, origin: dict, *, force: bool = False) -> Path:
    """Install the theme dir ``src`` as ``name`` under INSTALLED_THEMES_DIR.

    Atomic and overlap-safe: copies into a hidden staging sibling (preserving
    symlinks rather than dereferencing them), writes the origin marker, then
    swaps it into place with ``os.replace``. On any failure the staging copy is
    removed and the previously-installed theme is left untouched.
    """
    name = safe_theme_name(name)  # never let a name escape INSTALLED_THEMES_DIR
    src = Path(src)
    dest = INSTALLED_THEMES_DIR / name
    INSTALLED_THEMES_DIR.mkdir(parents=True, exist_ok=True)

    src_r, dest_r = src.resolve(), dest.resolve()
    if src_r == dest_r:
        # Installing a theme from its own installed location: just refresh origin.
        (dest / ORIGIN_FILE).write_text(json.dumps(origin, indent=2) + "\n", encoding="utf-8")
        return dest
    # Never let src and dest overlap, or rmtree(dest) could destroy the source.
    if src_r.is_relative_to(dest_r) or dest_r.is_relative_to(src_r):
        raise ThemeSecurityError(
            f"refusing install: source {src} overlaps destination {dest}"
        )
    if dest.exists() and not force:
        raise FileExistsError(
            f"theme {name!r} is already installed; pass --force to overwrite "
            f"(local edits will be lost)"
        )

    staging = INSTALLED_THEMES_DIR / f".{name}.staging"
    _force_rmtree(staging)
    try:
        shutil.copytree(src, staging, symlinks=True)
        (staging / ORIGIN_FILE).write_text(json.dumps(origin, indent=2) + "\n", encoding="utf-8")
        _force_rmtree(dest)
        os.replace(staging, dest)
    except BaseException:
        _force_rmtree(staging)
        raise
    return dest


def _is_zip(p: Path) -> bool:
    """True if ``p`` is an existing file that is a real zip archive."""
    return p.is_file() and zipfile.is_zipfile(p)


def _source_hash(p: Path) -> str | None:
    """Content fingerprint of a path/zip source so update can skip no-ops.

    ponytail: reads whole files into memory — themes are a few MB at most.
    A collection dir hashes as a unit, so one changed theme re-fetches all
    of its siblings installed from that dir; harmless and much simpler.
    """
    p = Path(p)
    h = hashlib.sha256()
    try:
        if p.is_file():
            h.update(p.read_bytes())
        elif p.is_dir():
            for f in sorted(p.rglob("*")):
                if f.is_file() and f.name != ORIGIN_FILE:
                    h.update(str(f.relative_to(p)).encode())
                    h.update(f.read_bytes())
        else:
            return None
    except OSError:
        return None
    return h.hexdigest()


def _confirm_replace(name: str, assume_yes: bool) -> bool:
    """Consent gate before ``update`` overwrites an installed theme's contents."""
    print(ansi.warn(f"updating {name} replaces its contents; local edits will be lost"))
    if assume_yes:
        return True
    if not sys.stdin.isatty():
        print(ansi.warn(f"skipped {name}: re-run interactively or pass --yes"))
        return False
    try:
        answer = input(f"  replace {name}? [y/N] ").strip().lower()
    except EOFError:
        return False
    return answer in ("y", "yes")


def _select_wanted(
    source: str, available: dict[str, Path], name: str | None, install_all: bool
) -> list[str]:
    """Pick which themes of a source to install; installing ALL needs consent."""
    if name:
        return [name]
    if len(available) <= 1 or install_all:
        return list(available)
    print(f"{source} contains {len(available)} themes: {', '.join(sorted(available))}")
    if not sys.stdin.isatty():
        raise GthemeError(
            "multiple themes in source; pass --all to install every one, "
            "or --name <theme> to pick one"
        )
    try:
        answer = input("  install all? [y/N, or one theme name] ").strip()
    except EOFError:
        answer = ""
    if answer.lower() in ("y", "yes", "a", "all"):
        return list(available)
    if answer in available:
        return [answer]
    raise GthemeError("nothing selected; pass --all or --name <theme>")


def _extract_zip(zip_path: Path, into: Path) -> Path:
    """Extract a theme .zip into ``into`` and return it as a collection root.

    ponytail: relies on the stdlib's member-path sanitization instead of
    re-validating each entry — ZipFile.extractall (since 3.6.2) strips leading
    slashes/drive and drops ``..`` components, so a malicious archive cannot
    write outside ``into`` (zip-slip safe). Stdlib zipfile also never restores
    symlinks, so there's no symlink-escape vector either.
    """
    print(ansi.bullet(f"unpacking {zip_path.name} …"))
    into.mkdir(parents=True, exist_ok=True)
    try:
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(into)
    except zipfile.BadZipFile as exc:
        raise GthemeError(f"not a valid zip archive: {zip_path} ({exc})")
    return into


def _root_theme_name(root: Path) -> str:
    """Name for a theme.toml-at-root dir: [meta].name beats the dir name.

    For zips/clones ``root`` is a temp dir ('unzipped'/'repo') — without this,
    every flat zip would install under the same leaked temp name. Falls back
    to the dir name when the manifest is unparsable or the name unsafe.
    """
    try:
        with (root / "theme.toml").open("rb") as fh:
            meta = tomllib.load(fh).get("meta", {})
        nm = meta.get("name") if isinstance(meta, dict) else None
        return safe_theme_name(nm) if isinstance(nm, str) else root.name
    except (OSError, tomllib.TOMLDecodeError, ThemeSecurityError):
        return root.name


def _themes_in_collection(root: Path) -> dict[str, Path]:
    """Map theme-name -> dir for a collection root or a single-theme dir."""
    # A repo/dir whose theme.toml sits at the root (no themes/ wrapper).
    if (root / "theme.toml").is_file():
        return {_root_theme_name(root): root}
    base = root / "themes" if (root / "themes").is_dir() else root
    out: dict[str, Path] = {}
    if not base.is_dir():
        return out
    for child in sorted(base.iterdir()):
        if (child / "theme.toml").is_file():
            out[child.name] = child
    return out


def _install_one(
    theme_dir: Path, name: str, origin: dict, *, force: bool, allow_unsafe: bool
) -> Path:
    """Validate a theme dir then copy it in. Raises on validation errors.

    Installs under [meta].name when it differs from ``name`` — registry
    discovery goes by directory name while the menu/CLI act by manifest name,
    so a mismatch would break every by-name action on the theme.
    """
    theme, errors, warnings = validate_dir(theme_dir)
    for w in warnings:
        print(ansi.warn(w))
    if errors and not allow_unsafe:
        bullets = "\n  - ".join(errors)
        raise ThemeValidationError(
            f"refusing to install {name!r}: theme failed validation:\n  - {bullets}\n"
            f"(pass --allow-unsafe to install anyway)"
        )
    if errors:
        print(ansi.warn(f"installing {name!r} despite {len(errors)} validation error(s) (--allow-unsafe)"))
    meta_name = getattr(getattr(theme, "meta", None), "name", None)
    if meta_name and meta_name != name:
        try:
            renamed = safe_theme_name(meta_name)
        except ThemeSecurityError:
            renamed = None  # unsafe manifest name: keep the requested one
        if renamed:
            print(ansi.warn(f"installing {name!r} as {renamed!r} (its [meta].name)"))
            name = renamed
    return _copy_theme(theme_dir, name, origin, force=force)


def install(
    source: str,
    name: str | None = None,
    insecure: bool = False,
    force: bool = False,
    allow_unsafe: bool = False,
    install_all: bool = False,
) -> list[str]:
    """Install one or more themes. Returns the installed theme names."""
    kw = {"force": force, "allow_unsafe": allow_unsafe}
    p = Path(source).expanduser()

    # 1) a path to a single theme directory
    if (p / "theme.toml").is_file():
        nm = name or p.name
        dest = _install_one(
            p, nm,
            {"type": "path", "source": str(p.resolve()), "hash": _source_hash(p)},
            **kw,
        )
        return [dest.name]  # _install_one may rename to [meta].name

    # 2) a git URL or repo / a .zip archive / a local collection directory
    #    (incl. a plain dir whose immediate children are theme dirs — the
    #    "unzipped one level too shallow" case).
    is_zip = _is_zip(p)
    if (
        _is_url(source) or is_zip or (p / ".git").is_dir()
        or (p.is_dir() and _themes_in_collection(p))
    ):
        with tempfile.TemporaryDirectory() as tmp:
            if _is_url(source):
                scheme = _check_scheme(source, insecure=insecure)
                root, commit = _git_clone(source, Path(tmp) / "repo")
                print(ansi.bullet(f"fetched {source} @ {commit[:12]}"))
                origin_base = {"type": "git", "source": source,
                               "commit": commit, "scheme": scheme}
            elif is_zip:
                # Zips are the sharing/download format -> untrusted origin type.
                root = _extract_zip(p, Path(tmp) / "unzipped")
                origin_base = {"type": "zip", "source": str(p.resolve()),
                               "hash": _source_hash(p)}
            else:
                root = p
                origin_base = {"type": "path", "source": str(p.resolve()),
                               "hash": _source_hash(p)}
            available = _themes_in_collection(root)
            if not available:
                raise FileNotFoundError(f"no themes found in {source}")
            wanted = _select_wanted(source, available, name, install_all)
            for nm in wanted:
                if nm not in available:
                    raise FileNotFoundError(
                        f"theme {nm!r} not in {source}; available: {', '.join(available) or '(none)'}"
                    )
            # Per-theme isolation: one bad theme must not abort the batch.
            installed: list[str] = []
            failed: list[str] = []
            for nm in wanted:
                try:
                    # origin keeps the selection key ``nm`` (what update() must
                    # re-pick from the source); the report uses the final dir name.
                    dest = _install_one(available[nm], nm, {**origin_base, "name": nm}, **kw)
                    installed.append(dest.name)
                except (GthemeError, OSError, shutil.Error) as exc:
                    failed.append(nm)
                    print(ansi.err(f"failed to install {nm}: {exc}"))
            if not installed:
                raise GthemeError(f"installed nothing from {source} ({len(failed)} failed)")
            return installed

    # 3) a bare name already in the bundled or installed collection -> copy in
    if BUNDLED_THEMES_DIR.is_dir() and (BUNDLED_THEMES_DIR / source / "theme.toml").is_file():
        src = BUNDLED_THEMES_DIR / source
        dest = _install_one(
            src, source,
            {"type": "bundled", "name": source, "hash": _source_hash(src)},
            **kw,
        )
        return [dest.name]
    if (INSTALLED_THEMES_DIR / source / "theme.toml").is_file():
        # Re-installing an already-installed bundled/local theme is a no-op refresh.
        return [source]

    # 4) An existing path with nothing installable in it: say so plainly —
    # "no such theme" would be factually wrong and the registry list a red herring.
    if p.is_dir():
        raise FileNotFoundError(
            f"'{p}' exists but contains no theme.toml (and no themes/ subdirectory) "
            f"— point gtheme at the folder that holds theme.toml"
        )
    if p.exists():
        raise GthemeError(f"'{p}' is a file but not a valid theme .zip archive")

    # 5) Not a path, URL, or known local theme: a bare name we can't resolve.
    # Do NOT silently clone the default remote (a typo would become a surprise
    # network fetch with a misleading error). Tell the user what IS available;
    # the CLI layer may offer the community collection as a consented fallback.
    from ..registry import discover

    raise FileNotFoundError(
        f"no such theme {source!r}; available: {', '.join(sorted(discover())) or '(none)'}\n"
        f"(to install your own, pass a path to a theme dir, a .zip "
        f"(e.g. ~/Downloads/forest.zip), or a git URL like {DEFAULT_REMOTE})"
    )


def update(
    name: str | None = None,
    insecure: bool = False,
    force: bool = False,
    assume_yes: bool = False,
) -> list[str]:
    """Refetch installed themes using their recorded origin.

    Each theme is refetched independently so one bad origin does not abort the
    rest (an explicitly named target re-raises instead, so the CLI can exit
    nonzero). Origins are skipped when unchanged — git via the remote HEAD,
    path/zip/bundled via the recorded content ``hash`` (unless ``force``) — so
    an up-to-date theme is never needlessly re-fetched and its local edits are
    preserved. A destructive re-fetch asks first (or needs ``assume_yes``).
    """
    updated: list[str] = []
    targets: list[Path] = []
    if name:
        targets = [INSTALLED_THEMES_DIR / name]
    elif INSTALLED_THEMES_DIR.is_dir():
        targets = [d for d in INSTALLED_THEMES_DIR.iterdir() if (d / ORIGIN_FILE).is_file()]
    for d in targets:
        origin = read_origin(d)
        if origin is None:
            print(ansi.warn(f"skipping {d.name}: missing or unreadable origin"))
            continue
        otype = origin.get("type")
        src = origin.get("source")
        nm = origin.get("name", d.name)
        try:
            if otype == "bundled":
                bsrc = BUNDLED_THEMES_DIR / nm
                if not (bsrc / "theme.toml").is_file():
                    # Dropped from the shipped collection: skip like a vanished
                    # path origin — never warn + claim a no-op "updated".
                    print(ansi.warn(f"skipping {d.name}: {nm!r} is no longer in the bundled collection"))
                    continue
                cur = _source_hash(bsrc)
                if cur and not force and cur == origin.get("hash"):
                    print(ansi.bullet(f"{d.name} already up to date"))
                    continue
                if not _confirm_replace(d.name, assume_yes):
                    continue
                install(nm, insecure=insecure, force=True)
            elif otype == "git" and src:
                head = _remote_head(src)
                if head and not force and head == origin.get("commit"):
                    print(ansi.bullet(f"{d.name} already up to date ({head[:12]})"))
                    continue
                if not _confirm_replace(d.name, assume_yes):
                    continue
                install(src, name=nm, insecure=insecure, force=True)
            elif otype in ("path", "zip") and src:
                sp = Path(src)
                if not _is_zip(sp) and not (sp / "theme.toml").is_file() \
                        and not (sp.is_dir() and _themes_in_collection(sp)):
                    print(ansi.warn(f"skipping {d.name}: origin path no longer exists ({src})"))
                    continue
                cur = _source_hash(sp)
                if cur and not force and cur == origin.get("hash"):
                    print(ansi.bullet(f"{d.name} already up to date"))
                    continue
                if not _confirm_replace(d.name, assume_yes):
                    continue
                install(src, name=nm, insecure=insecure, force=True)
            else:
                print(ansi.warn(f"skipping {d.name}: origin has no usable source"))
                continue
        except Exception as exc:  # one bad origin must not abort the rest…
            if name:  # …but an explicit target failing must not exit 0
                raise
            print(ansi.err(f"failed to update {d.name}: {exc}"))
            continue
        updated.append(d.name)
    return updated
