#!/usr/bin/env python3
"""Draw the NIGHTBLOOM wallpaper.

The picture that ships with the NIGHTBLOOM Look is generated by this script, so
it is ours to give away: no stock frame, no licence attached, and reproducible
from source — run it and the same file comes back.

    .venv/bin/python tools/gen_nightbloom_wallpaper.py

It is one scene: a long, low glass conservatory lit from inside, standing
across still water on a green night. Nothing in it is drawn as an outline —
the building exists only as the light coming through its glazing, cut by the
dark bars of its own frame, which is what keeps a handful of straight lines
from reading as a diagram.

Layers, bottom up: the night wash; cool light high in the sky; the glasshouse
itself (walls, gable roof, mullions, rafters); the bloom escaping it; two faint
shafts of light leaning out through the damp air; its reflection, stretched and
rippled in the water; low mist along the far bank; fireflies, thick in the warm
air by the glass and sparse out in the dark; a vignette; and a whisper of
grain, which is also what stops a 2560-pixel gradient banding on a real screen.

Colours come from the Look's own palette (``themes/nightbloom/theme.toml``).
Everything is seeded, so the output is deterministic.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

WIDTH = 2560
HEIGHT = 1440
SEED = 20260825

# --- the Look's palette (themes/nightbloom/theme.toml [palette]) -------------
VOID = "#0A100C"
SURFACE = "#0F1712"
GLASSLINE = "#2A3D31"
VERDIGRIS = "#3E7A63"
JADE = "#52E0A4"
TEAL = "#7BD8C4"
AMBER = "#F5C04A"
GROWLIGHT = "#C77DFF"
BONE = "#E8E4D6"

# --- the scene, in fractions of the frame -----------------------------------
# The glasshouse sits off to the right of centre and low, which leaves the left
# two-thirds open. That is deliberate: a wallpaper has to share the screen with
# desktop icons, and a subject dead in the middle fights everything put on it.
WATERLINE = 0.700  # where the building meets its own reflection
EAVE = 0.600  # top of the glass wall
RIDGE = 0.532  # the ridge of the gable
LEFT = 0.534
RIGHT = 0.750


def rgb(hex_colour: str) -> np.ndarray:
    """'#0A100C' -> float array [0.039, 0.063, 0.047]."""
    h = hex_colour.lstrip("#")
    return np.array([int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4)], dtype=np.float64)


def _box_blur_1d(field: np.ndarray, radius: int, axis: int) -> np.ndarray:
    """Moving average of width 2r+1 along one axis, edges clamped."""
    if radius < 1:
        return field
    a = np.moveaxis(field, axis, -1)
    pad = np.pad(a, [(0, 0)] * (a.ndim - 1) + [(radius + 1, radius)], mode="edge")
    c = np.cumsum(pad, axis=-1)
    out = (c[..., 2 * radius + 1 :] - c[..., : -(2 * radius + 1)]) / (2 * radius + 1)
    return np.moveaxis(out, -1, axis)


def blur(field: np.ndarray, radius: float) -> np.ndarray:
    """Gaussian-ish blur: three box passes, which is the classic approximation.

    PIL's own GaussianBlur refuses float images, and the whole picture is built
    in float on purpose — 8-bit intermediates band in darks this deep.
    """
    r = max(1, int(round(radius * 0.62)))
    out = field
    for axis in (0, 1):
        for _ in range(3):
            out = _box_blur_1d(out, r, axis)
    return out


def smooth_noise(h: int, w: int, cells: tuple[int, int], rng: np.random.Generator) -> np.ndarray:
    """Band-limited noise in 0..1, by upsampling a small random field."""
    from PIL import Image

    small = rng.random((cells[0], cells[1])).astype(np.float32)
    return np.asarray(
        Image.fromarray(small, mode="F").resize((w, h), Image.Resampling.BICUBIC), dtype=np.float64
    )


def vertical_wash(h: int, w: int, stops: list[tuple[float, np.ndarray]]) -> np.ndarray:
    """Interpolate colours down the picture. stops = [(0..1 from top, colour)]."""
    ys = np.linspace(0.0, 1.0, h)
    positions = np.array([p for p, _ in stops])
    colours = np.stack([c for _, c in stops])
    out = np.empty((h, 3))
    for channel in range(3):
        out[:, channel] = np.interp(ys, positions, colours[:, channel])
    return np.repeat(out[:, None, :], w, axis=1)


def blob(yy: np.ndarray, xx: np.ndarray, centre: tuple[float, float], sigma: tuple[float, float]) -> np.ndarray:
    """A soft elliptical light, peak 1.0 at the centre."""
    cx, cy = centre
    sx, sy = sigma
    return np.exp(-(((xx - cx) ** 2) / (2 * sx * sx) + ((yy - cy) ** 2) / (2 * sy * sy)))


def soft_band(v: np.ndarray, lo: float, hi: float, feather: float) -> np.ndarray:
    """1.0 between lo and hi, easing to 0 over `feather` either side."""
    return np.clip((v - lo) / feather, 0.0, 1.0) * np.clip((hi - v) / feather, 0.0, 1.0)


def build_glasshouse(h: int, w: int, yy: np.ndarray, xx: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """The lit glazing, as a 0..1 emission field.

    The shape is a long shallow gable on a low glass wall. Light is strongest
    low down — lamps sit among the planting, not in the roof — and each bay
    carries a slightly different amount, because no two panes of a real
    conservatory are ever lit the same.
    """
    x0, x1 = w * LEFT, w * RIGHT
    y_base, y_eave, y_ridge = h * WATERLINE, h * EAVE, h * RIDGE
    half = (x1 - x0) / 2.0
    mid = (x0 + x1) / 2.0

    # The silhouette: a glass wall below the eaves, and above them a roof that
    # rises to a RIDGE running horizontally along the building. A plain
    # triangle would read as the front of a house; the flat ridge with a slope
    # falling away either side is what a long conservatory actually looks like.
    ridge_half = half * 0.34
    roof_top = y_ridge + np.clip(
        (np.abs(xx - mid) - ridge_half) / (half - ridge_half), 0.0, 1.0
    ) * (y_eave - y_ridge)
    inside_x = soft_band(xx, x0, x1, 2.0)
    inside_y = np.clip((y_base - yy) / 2.0, 0.0, 1.0) * np.clip((yy - roof_top) / 2.0, 0.0, 1.0)
    shell = inside_x * inside_y

    # Brightness gradient. The lamps stand among the planting, so the bottom of
    # the glass is full and the gable above the eaves is nearly dark — which is
    # the difference between a conservatory at night and a lit shed.
    depth = np.clip((y_base - yy) / (y_base - y_ridge), 0.0, 1.0)
    lum = 0.10 + 0.90 * np.exp(-((depth / 0.36) ** 1.5))
    # Two runs of staging inside, catching the light from underneath.
    for at, amount in ((0.30, 0.20), (0.62, 0.11)):
        lum = lum * (1.0 + amount * np.exp(-(((depth - at) / 0.055) ** 2)))

    # Bay-by-bay variation, so the run of panes has a pulse to it, and a
    # left-to-right lean, because one end of a real glasshouse is always
    # further from the lamps than the other.
    bays = 15
    bay_w = (x1 - x0) / bays
    bay_idx = np.clip(((xx - x0) / bay_w).astype(np.int64), 0, bays - 1)
    bay_gain = 0.42 + 0.62 * rng.random(bays)
    bay_gain[5] *= 1.50  # the doorway
    lum = lum * bay_gain[bay_idx] * (0.72 + 0.42 * (1.0 - (xx - x0) / (x1 - x0)))

    light = shell * lum

    # The frame, taken back OUT of the light: mullions running the full height
    # into the gable, a transom across the wall, the roof slopes, the ridge and
    # the corner posts. Mullions that stop at the eaves make a house; mullions
    # that carry on into the gable make a glasshouse.
    frame = np.zeros((h, w))

    def bars(coord: np.ndarray, pitch: float, width: float, strength: float) -> np.ndarray:
        d = np.abs(coord / pitch - np.round(coord / pitch)) * pitch
        return np.clip(1.0 - (d - width * 0.5), 0.0, 1.0) * strength

    frame = np.maximum(frame, bars(xx - x0, bay_w, 3.0, 0.90))
    frame = np.maximum(frame, bars(xx - x0 - bay_w * 0.5, bay_w, 1.8, 0.42))  # thin astragals
    frame = np.maximum(frame, np.clip(2.2 - np.abs(yy - (y_base * 0.42 + y_eave * 0.58)), 0.0, 1.0) * 0.62)
    frame = np.maximum(frame, np.clip(2.4 - np.abs(yy - y_eave), 0.0, 1.0) * 0.88)  # the eaves
    frame = np.maximum(frame, np.clip(2.6 - np.abs(yy - roof_top), 0.0, 1.0) * 0.95)  # the roof slopes
    frame = np.maximum(frame, np.clip(3.0 - np.abs(xx - x0), 0.0, 1.0) * 0.95)
    frame = np.maximum(frame, np.clip(3.0 - np.abs(xx - x1), 0.0, 1.0) * 0.95)
    frame = np.maximum(frame, np.clip(2.6 - np.abs(yy - y_base), 0.0, 1.0) * 0.95)
    light = light * (1.0 - 0.88 * frame * shell)

    # A ridge cap: the little raised vent that sits on the apex of a real
    # conservatory roof, and the one thing that stops the gable reading as a
    # barn. It has to hug the ridge — floated above it, it reads as a mistake.
    cap_h = (y_eave - y_ridge) * 0.30
    lantern = soft_band(xx, mid - ridge_half * 0.80, mid + ridge_half * 0.80, 2.0)
    lantern *= soft_band(yy, y_ridge - cap_h, y_ridge + 1.0, 1.6)
    lantern *= 1.0 - 0.80 * bars(xx - x0, bay_w, 2.6, 1.0)
    light = np.maximum(light, lantern * 0.34)

    # Two lamps standing in the planting, seen straight through the glass.
    for at_x, at_y, sx, sy, gain in (
        (0.32, 0.80, 0.030, 0.055, 0.55),
        (0.66, 0.86, 0.024, 0.045, 0.40),
    ):
        lamp = np.exp(
            -((((xx - (x0 + (x1 - x0) * at_x)) / (w * sx)) ** 2)
              + (((yy - (y_ridge + (y_base - y_ridge) * at_y)) / (h * sy)) ** 2))
        )
        light = light + lamp * shell * gain

    return light


def fireflies(h: int, w: int, rng: np.random.Generator, warmth: np.ndarray) -> np.ndarray:
    """Small warm cores with a wide, faint halo. Returns an RGB light field."""
    light = np.zeros((h, w, 3))
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)

    amber, warm_white = rgb(AMBER), rgb(BONE)
    jade, teal, growlight = rgb(JADE), rgb(TEAL), rgb(GROWLIGHT)

    def add(cx: float, cy: float, core: float, halo: float, gain: float, colour: np.ndarray) -> None:
        reach = halo * 3.0
        lo_x, hi_x = max(0, int(cx - reach)), min(w, int(cx + reach) + 1)
        lo_y, hi_y = max(0, int(cy - reach)), min(h, int(cy + reach) + 1)
        if lo_x >= hi_x or lo_y >= hi_y:
            return
        d2 = (xx[lo_y:hi_y, lo_x:hi_x] - cx) ** 2 + (yy[lo_y:hi_y, lo_x:hi_x] - cy) ** 2
        body = np.exp(-d2 / (2.0 * core * core))
        halofield = np.exp(-d2 / (2.0 * halo * halo)) * 0.10
        field = (body + halofield) * gain
        tint = colour[None, None, :] * (1.0 - 0.62 * body[..., None]) + warm_white[None, None, :] * (
            0.62 * body[..., None]
        )
        light[lo_y:hi_y, lo_x:hi_x] += field[..., None] * tint

    # Two loose swarms either side of the glasshouse, plus strays through the
    # dark. Insects group; dust scatters evenly, and this must not read as dust.
    placements: list[tuple[float, float]] = []
    for cx, cy, sx, sy, n in (
        (w * 0.815, h * 0.545, w * 0.070, h * 0.070, 11),
        (w * 0.455, h * 0.585, w * 0.055, h * 0.050, 7),
        (w * 0.170, h * 0.300, w * 0.090, h * 0.090, 8),
    ):
        placements += [(rng.normal(cx, sx), rng.normal(cy, sy)) for _ in range(n)]
    placements += [(w * rng.random(), h * (0.14 + 0.52 * rng.beta(1.5, 1.3))) for _ in range(16)]
    # A few down by the water on the open side, so the left of the frame is
    # quiet rather than empty.
    placements += [(w * (0.03 + 0.36 * rng.random()), h * (0.60 + 0.07 * rng.random())) for _ in range(6)]

    for cx, cy in placements:
        if not (-30 < cx < w + 30 and 0 < cy < h * 0.695):
            continue
        lit = float(warmth[int(np.clip(cy, 0, h - 1)), int(np.clip(cx, 0, w - 1))])
        core = 1.15 + 1.5 * rng.random() + 0.9 * lit
        # Out in the dark a firefly is all core and almost no halo; near the
        # glasshouse the damp air around it lights up too. Getting that the
        # wrong way round is what makes rendered fireflies look like dust.
        halo = core * (4.0 + 6.0 * rng.random() + 14.0 * lit)
        gain = (0.42 + 0.60 * rng.random()) * (0.72 + 0.80 * lit)
        roll = rng.random()
        colour = teal if roll < 0.07 else jade if roll < 0.11 else growlight if roll < 0.125 else amber
        add(cx, cy, core, halo, gain, colour)

    # A few big, faint, out-of-focus ones, to put air between the layers. They
    # stay near the glasshouse: a bokeh circle in empty dark reads as a smudge
    # on the lens, not as an insect drifting past the light.
    for _ in range(5):
        add(w * (0.42 + 0.40 * rng.random()), h * (0.40 + 0.24 * rng.random()),
            15.0 + 16.0 * rng.random(), 52.0, 0.016 + 0.014 * rng.random(), amber)

    return light


def render() -> np.ndarray:
    rng = np.random.default_rng(SEED)
    h, w = HEIGHT, WIDTH
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    warm, cool = rgb(AMBER), rgb(TEAL)

    # 1. The night. Green-teal all the way down, never blue and never black;
    #    amber only reads as warm if the ground it sits on stays cool.
    img = vertical_wash(
        h,
        w,
        [
            (0.00, rgb("#071009")),
            (0.30, rgb("#0A150F")),
            (0.58, rgb("#0C1813")),
            (0.700, rgb(SURFACE)),
            (0.84, rgb("#0A1512")),
            (1.00, rgb("#050B09")),
        ],
    )

    # 2. Cool light high in the sky — a moon somewhere off to the left, behind
    #    wet air.
    img += blob(yy, xx, (w * 0.22, h * 0.06), (w * 0.34, h * 0.34))[..., None] * rgb(VERDIGRIS) * 0.105
    img += blob(yy, xx, (w * 0.90, h * -0.04), (w * 0.26, h * 0.30))[..., None] * cool * 0.050

    # 3. The glasshouse. Kept dim on purpose: in this palette amber is an
    #    accent, and an accent that fills the frame stops being one.
    glass = build_glasshouse(h, w, yy, xx, rng)
    img += glass[..., None] * warm * 0.42
    img += (glass**2.6)[..., None] * rgb(BONE) * 0.22  # the brightest panes go warm-white

    # 4. The bloom around it: three passes so the falloff is not one flat halo.
    bloom = blur(glass, 9.0) * 0.55 + blur(glass, 38.0) * 0.85 + blur(glass, 150.0) * 1.30
    img += bloom[..., None] * warm * 0.205

    # 5. Two shafts of light leaning out through the damp air — the only
    #    diagonals in the sky. Faint enough to be weather, not an effect.
    mid_x, src_y = w * (LEFT + RIGHT) / 2.0, h * (WATERLINE - 0.055)
    for lean, strength in ((-0.70, 0.042), (0.42, 0.030)):
        u = (xx - mid_x) - lean * (src_y - yy)
        shaft = np.exp(-((u / (w * 0.070)) ** 2)) * np.clip((src_y - yy) / (h * 0.40), 0.0, 1.0)
        shaft *= np.clip(1.0 - (src_y - yy) / (h * 0.52), 0.0, 1.0) ** 1.4
        img += shaft[..., None] * warm * strength

    # 6. The reflection. Mirror the building about the waterline, stretch it
    #    down, ripple it sideways, and keep it far dimmer than the source —
    #    still water gives back maybe a third of what it is given.
    wl = int(h * WATERLINE)
    src = np.flipud(glass[:wl] + bloom[:wl] * 0.55)
    rows = np.clip((np.arange(h - wl) * 0.86).astype(int), 0, src.shape[0] - 1)
    refl = np.zeros((h, w))
    refl[wl:] = src[rows]
    ripple = smooth_noise(h, w, (44, 5), rng)
    shift = ((ripple - 0.5) * 34.0).astype(int)
    cols = np.clip(np.arange(w)[None, :] + shift, 0, w - 1)
    refl = np.take_along_axis(refl, cols, axis=1)
    refl = blur(refl, 7.0)
    fade = np.clip(1.0 - (yy - h * WATERLINE) / (h * 0.26), 0.0, 1.0) ** 1.6
    refl *= fade * (yy >= h * WATERLINE) * (0.42 + 0.95 * ripple)
    img += refl[..., None] * warm * 0.185

    # 7. Mist along the far bank — it softens the join between the building and
    #    the water and puts distance behind everything.
    mist = np.exp(-(((yy - h * (WATERLINE - 0.014)) / (h * 0.048)) ** 2))
    mist *= 0.25 + 0.75 * smooth_noise(h, w, (4, 15), rng)
    img += mist[..., None] * (cool * 0.45 + warm * 0.55) * 0.034

    # 7b. The far bank behind the mist: a low dark line of planting on the
    #     other side of the water, which is what gives the left of the picture
    #     a distance instead of a void.
    bank_h = h * (0.004 + 0.030 * smooth_noise(h, w, (1, 13), rng))
    bank = np.clip((yy - (h * WATERLINE - bank_h)) / (h * 0.006), 0.0, 1.0)
    bank *= np.clip((h * WATERLINE + 3.0 - yy) / (h * 0.006), 0.0, 1.0)
    bank *= np.clip(1.0 - (np.abs(xx - w * 0.52) / (w * 0.52)) ** 2.2, 0.0, 1.0)
    img *= (1.0 - 0.30 * blur(bank, 15.0))[..., None]

    # 7c. Ripples. Long, flat, low-contrast bands lying on the water, brightest
    #     where the reflection is and gone by the bottom of the frame.
    ripples = smooth_noise(h, w, (150, 2), rng) - 0.5
    ripples *= np.clip((yy - h * WATERLINE) / (h * 0.012), 0.0, 1.0)
    ripples *= np.clip(1.0 - (yy - h * WATERLINE) / (h * 0.26), 0.0, 1.0) ** 1.4
    img += (ripples * (0.020 + 0.55 * refl))[..., None] * (warm * 0.6 + cool * 0.4)

    # 8. Fireflies. Their brightness follows the light in the air around them.
    img += fireflies(h, w, rng, np.clip(bloom * 1.6, 0.0, 1.0))

    # 9. The planting, close to the eye and well out of focus: a dark mass along
    #    the bottom and a canopy overhead. It frames the scene, gives the
    #    picture a foreground to have depth against, and — the practical part —
    #    keeps the top bar and the dock sitting on quiet, dark pixels.
    leaf_top = smooth_noise(h, w, (2, 34), rng) * 0.62 + smooth_noise(h, w, (2, 9), rng) * 0.38
    canopy = np.clip((h * (0.012 + 0.088 * leaf_top) - yy) / (h * 0.030), 0.0, 1.0)
    canopy = np.maximum(canopy, blob(yy, xx, (w * 0.04, h * -0.04), (w * 0.14, h * 0.10)) * 1.3)
    canopy = np.maximum(canopy, blob(yy, xx, (w * 0.95, h * -0.02), (w * 0.15, h * 0.09)) * 1.2)
    leaf_bot = smooth_noise(h, w, (2, 28), rng) * 0.62 + smooth_noise(h, w, (2, 8), rng) * 0.38
    undergrowth = np.clip((yy - h * (0.985 - 0.105 * leaf_bot)) / (h * 0.035), 0.0, 1.0)
    undergrowth = np.maximum(undergrowth, blob(yy, xx, (w * 0.10, h * 1.06), (w * 0.22, h * 0.13)) * 1.4)
    undergrowth = np.maximum(undergrowth, blob(yy, xx, (w * 0.88, h * 1.09), (w * 0.26, h * 0.15)) * 1.3)
    planting = np.clip(blur(np.clip(canopy + undergrowth, 0.0, 1.0), 34.0), 0.0, 1.0)
    img *= (1.0 - 0.72 * planting)[..., None]
    img += planting[..., None] * rgb("#060D0A") * 0.60

    # 10. Vignette.
    r = np.sqrt(((xx - w * 0.46) / (w * 0.64)) ** 2 + ((yy - h * 0.50) / (h * 0.74)) ** 2)
    img *= (1.0 - 0.34 * np.clip(r, 0.0, 1.7) ** 2.2)[..., None]

    # 11. Grain: stops the wide gradient banding, and keeps the picture from
    #     looking like a rendering.
    grain = rng.normal(0.0, 1.0, (h, w))
    grain = (grain + np.roll(grain, 1, axis=0) + np.roll(grain, 1, axis=1)) / 3.0
    img += grain[..., None] * (0.0038 + 0.0090 * np.clip(img.mean(axis=2), 0.0, 1.0))[..., None]

    return np.clip(img, 0.0, 1.0)


def main() -> int:
    parser = argparse.ArgumentParser(description="Draw the NIGHTBLOOM wallpaper.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "themes"
        / "nightbloom"
        / "wallpaper"
        / "nightbloom-glasshouse.png",
        help="where to write the PNG",
    )
    args = parser.parse_args()

    from PIL import Image

    img = render()
    out = np.clip(np.round(img * 255.0), 0, 255).astype(np.uint8)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(out, mode="RGB").save(args.output, format="PNG", optimize=True)
    print(f"wrote {args.output} ({args.output.stat().st_size / 1024 / 1024:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
