#!/usr/bin/env python3
"""Enumerate every core-GNOME setting that exists, so none can be forgotten.

DESIGN.md A7/F14: "nothing was left out" is a claim a test checks, not a claim
someone remembers. The test needs a list of everything there *is* — and that
list has to come from a real desktop, not from a document, because a document
goes stale and a desktop does not.

This reads the live session **strictly read-only**: ``gsettings
list-recursively`` over the schema allowlist below, which reads the store and
never writes to it. The output, ``data/domains/universe.txt``, is one line per
key::

    org.gnome.desktop.interface<TAB>color-scheme<TAB>s

``data/domains/coverage.toml`` must then disposition every one of those lines
as ``surfaced(<page>)``, ``compound(<op>)``, ``floor``, ``excluded(<reason>)``
or ``delegated(<target>)``, and the coverage test fails on any key with no
disposition at all.

    ./.venv/bin/python tools/gen_coverage_universe.py
    ./.venv/bin/python tools/gen_coverage_universe.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "data" / "domains" / "universe.txt"

#: Schemas whose keys are part of gtheme's surface, from gnome-domains.md §8.
#: Everything under ``org.gnome.desktop.*`` that the sweep found relevant, plus
#: the non-``desktop`` schemas that also carry customisation: the shell itself,
#: mutter, and the settings-daemon plugins that own night light, power and the
#: XSETTINGS override escape hatch.
#:
#: Prefixes ending in ``.*`` pull in every installed schema underneath.
SCHEMA_ALLOWLIST: tuple[str, ...] = (
    "org.gnome.desktop.a11y",
    "org.gnome.desktop.a11y.applications",
    "org.gnome.desktop.a11y.interface",
    "org.gnome.desktop.a11y.keyboard",
    "org.gnome.desktop.a11y.magnifier",
    "org.gnome.desktop.a11y.mouse",
    "org.gnome.desktop.app-folders",
    "org.gnome.desktop.background",
    "org.gnome.desktop.break-reminders.*",
    "org.gnome.desktop.calendar",
    "org.gnome.desktop.datetime",
    "org.gnome.desktop.default-applications.*",
    "org.gnome.desktop.input-sources",
    "org.gnome.desktop.interface",
    "org.gnome.desktop.lockdown",
    "org.gnome.desktop.media-handling",
    "org.gnome.desktop.notifications",
    "org.gnome.desktop.peripherals.*",
    "org.gnome.desktop.privacy",
    "org.gnome.desktop.screen-time-limits",
    "org.gnome.desktop.screensaver",
    "org.gnome.desktop.search-providers",
    "org.gnome.desktop.session",
    "org.gnome.desktop.sound",
    "org.gnome.desktop.thumbnail-cache",
    "org.gnome.desktop.thumbnailers",
    "org.gnome.desktop.wm.keybindings",
    "org.gnome.desktop.wm.preferences",
    "org.gnome.mutter",
    "org.gnome.mutter.keybindings",
    "org.gnome.mutter.wayland",
    "org.gnome.settings-daemon.plugins.color",
    "org.gnome.settings-daemon.plugins.media-keys",
    "org.gnome.settings-daemon.plugins.power",
    "org.gnome.settings-daemon.plugins.xsettings",
    "org.gnome.shell",
    "org.gnome.shell.app-switcher",
    "org.gnome.shell.keybindings",
    "org.gnome.shell.window-switcher",
    "org.gnome.shell.world-clocks",
    "org.gnome.system.location",
)

_HEADER = """\
# GENERATED by tools/gen_coverage_universe.py — do not edit by hand.
#
# Every core-GNOME setting that exists on a GNOME {shell} desktop, read from a
# live session with `gsettings list-recursively` (read-only). One line per key:
#
#     schema<TAB>key<TAB>type
#
# data/domains/coverage.toml must disposition every one of these. A key with no
# disposition fails the coverage test, which is what makes "nothing was left
# out" checkable instead of aspirational.
#
# schemas: {schemas}   keys: {keys}
"""


def list_installed_schemas() -> set[str]:
    result = subprocess.run(
        ["gsettings", "list-schemas"],
        capture_output=True,
        text=True,
        check=True,
        env={**os.environ, "LC_ALL": "C"},
    )
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


def resolve_allowlist(installed: set[str]) -> tuple[list[str], list[str]]:
    """Expand ``.*`` prefixes against what is installed.

    Returns ``(schemas, missing)`` — ``missing`` are allowlist entries with no
    installed match, reported so a typo in the list is visible rather than
    silently narrowing the universe.
    """
    chosen: set[str] = set()
    missing: list[str] = []
    for entry in SCHEMA_ALLOWLIST:
        if entry.endswith(".*"):
            prefix = entry[:-1]
            matched = {s for s in installed if s.startswith(prefix)}
            base = entry[:-2]
            if base in installed:
                matched.add(base)
            if matched:
                chosen |= matched
            else:
                missing.append(entry)
        elif entry in installed:
            chosen.add(entry)
        else:
            missing.append(entry)
    return sorted(chosen), missing


_LINE_RE = re.compile(r"^(?P<schema>\S+) (?P<key>\S+) (?P<value>.*)$")


def keys_of(schema: str) -> list[tuple[str, str, str]]:
    """``(schema, key, type)`` for one schema. READ-ONLY.

    ``list-recursively`` prints current values, not types, so the type comes
    from ``gsettings range``, which is also a read. Neither command writes.
    """
    listed = subprocess.run(
        ["gsettings", "list-recursively", schema],
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "LC_ALL": "C"},
    )
    if listed.returncode != 0:
        return []

    out = []
    for line in listed.stdout.splitlines():
        match = _LINE_RE.match(line)
        if not match or match.group("schema") != schema:
            continue
        key = match.group("key")
        out.append((schema, key, key_type(schema, key)))
    return sorted(set(out))


def key_type(schema: str, key: str) -> str:
    """The key's type, or ``?`` when it cannot be determined.

    ``gsettings range`` has four output shapes, and they are not all one word::

        type s                  a plain key
        range d -1.0 1.0        a key with bounds, all on ONE line
        enum\\n'a'\\n'b'          a choice, values on the following lines
        flags\\n'a'\\n'b'         a set of choices

    ``enum`` and ``flags`` are reported as such rather than as their underlying
    ``s``, because which of the two a key is decides how it is drawn. For a
    bounded key the underlying type is reported; the bounds themselves belong
    in the descriptor's clamps, where a person can see and argue with them.
    """
    result = subprocess.run(
        ["gsettings", "range", schema, key],
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "LC_ALL": "C"},
    )
    if result.returncode != 0:
        return "?"
    lines = result.stdout.strip().splitlines()
    if not lines:
        return "?"
    head = lines[0].strip()
    words = head.split()
    if not words:
        return "?"
    if words[0] == "type" and len(words) >= 2:
        return " ".join(words[1:])
    if words[0] == "range" and len(words) >= 2:
        return words[1]
    if words[0] in {"enum", "flags"}:
        return words[0]
    return "?"


def render(rows: list[tuple[str, str, str]], schemas: list[str], shell: str) -> str:
    header = _HEADER.format(shell=shell, schemas=len(schemas), keys=len(rows))
    body = "\n".join(f"{schema}\t{key}\t{type_}" for schema, key, type_ in rows)
    return header + body + "\n"


def shell_version() -> str:
    exe = shutil.which("gnome-shell")
    if not exe:
        return "unknown"
    result = subprocess.run([exe, "--version"], capture_output=True, text=True, check=False)
    parts = result.stdout.strip().split()
    return parts[-1].split(".")[0] if parts else "unknown"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed file is stale")
    args = parser.parse_args(argv)

    if shutil.which("gsettings") is None:
        print("gsettings is not installed — cannot enumerate the universe", file=sys.stderr)
        return 1

    installed = list_installed_schemas()
    schemas, missing = resolve_allowlist(installed)
    for entry in missing:
        print(f"note: allowlist entry {entry!r} matches nothing installed here", file=sys.stderr)

    rows: list[tuple[str, str, str]] = []
    for schema in schemas:
        rows.extend(keys_of(schema))
    rows.sort()

    text = render(rows, schemas, shell_version())
    current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else None

    if args.check:
        if current != text:
            print("data/domains/universe.txt is stale", file=sys.stderr)
            print("run: python tools/gen_coverage_universe.py", file=sys.stderr)
            return 1
        print("universe.txt is up to date")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}: {len(rows)} keys from {len(schemas)} schemas")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
