#!/usr/bin/env python3
"""Draw the DAYBREAK and HEARTH wallpapers.

Both pictures that ship with these two Looks are generated by this script, so
they are ours to give away: no stock photograph, no licence attached, and
reproducible from source — run it and the same two files come back.

    .venv/bin/python tools/gen_daylight_wallpapers.py

Neither is a scene. They are light: a low sun coming up behind a glasshouse in
DAYBREAK, a fire seen from across a warm room in HEARTH — in both cases drawn
as nothing but a graded wash, a soft source of light low on the right, and a
fan of wide shafts leaning out of it. Shafts rather than lines: a line at this
size reads as a diagram, and a shaft soft enough reads as light.

The light source sits low and to the right in both, which leaves the upper
left two-thirds of the frame open. That is deliberate: a wallpaper shares the
screen with desktop icons and app windows, and a subject in the middle fights
everything put on top of it.

Colours come from each Look's own ``[palette]`` block, repeated here as
constants so the script can be read on its own. Everything is deterministic:
there is no randomness beyond a half-a-level ordered dither, which exists only
to stop a 2560-pixel gradient banding on a real screen and is invisible.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image

WIDTH = 2560
HEIGHT = 1440

REPO_ROOT = Path(__file__).resolve().parents[1]


def rgb(hex_colour: str) -> np.ndarray:
    """``'#F7F3EA'`` becomes a float array in 0..1."""
    h = hex_colour.lstrip("#")
    return np.array([int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4)], dtype=np.float64)


def smoothstep(t: np.ndarray) -> np.ndarray:
    t = np.clip(t, 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def _grids() -> tuple[np.ndarray, np.ndarray]:
    """``(x, y)`` in 0..1, with ``x`` corrected for the frame's aspect ratio.

    Distances are measured in units of the frame *height*, so a circle drawn
    here is round on the screen rather than an ellipse 16 units wide and 9 tall.
    """
    y, x = np.mgrid[0:HEIGHT, 0:WIDTH].astype(np.float64)
    return x / HEIGHT, y / HEIGHT


def _draw(
    *,
    sky: str,
    horizon: str,
    ground: str,
    glow: str,
    ray: str,
    source: tuple[float, float],
    glow_radius: float,
    glow_strength: float,
    ray_angles: tuple[float, ...],
    ray_width: float,
    ray_strength: float,
    ray_reach: float,
    horizon_at: float,
    vignette: float,
) -> np.ndarray:
    """One picture, bottom layer up. Returns an ``(H, W, 3)`` float image."""
    x, y = _grids()
    aspect = WIDTH / HEIGHT

    def over(base: np.ndarray, colour: np.ndarray, alpha: np.ndarray) -> np.ndarray:
        """Lay ``colour`` over ``base``. A blend, never an addition.

        Adding light to an already-light picture only ever ends at white, and
        a white rectangle is what the first draft of both of these was.
        """
        a = np.clip(alpha, 0.0, 1.0)[..., None]
        return base * (1.0 - a) + colour * a

    # 1. the wash: three stops up the frame, eased, so no horizon has an edge
    #    a person can find and call a line.
    upper = smoothstep((y - 0.02) / horizon_at)[..., None]
    lower = smoothstep((y - horizon_at) / (1.02 - horizon_at))[..., None]
    image = rgb(sky) * (1.0 - upper) + rgb(horizon) * upper
    image = image * (1.0 - lower) + rgb(ground) * lower

    # 2. the light itself: one soft source, low and right of centre, sitting
    #    mostly below the bottom edge so what shows is the top of it.
    sx, sy = source[0] * aspect, source[1]
    distance = np.hypot(x - sx, y - sy)
    image = over(image, rgb(glow), np.exp(-((distance / glow_radius) ** 2)) * glow_strength)

    # 3. the fan: shafts of light leaning out of that source — through a
    #    glasshouse roof in one picture, across a warm room in the other.
    #    Angles are measured from straight up and spaced unevenly on purpose;
    #    an even fan reads as a machine-drawn diagram.
    theta = np.arctan2(x - sx, sy - y)
    fan = np.zeros_like(theta)
    for index, angle in enumerate(ray_angles):
        weight = 1.0 if index % 2 == 0 else 0.66
        fan = fan + weight * np.exp(-(((theta - angle) / ray_width) ** 2))
    # A shaft starts a little way out from the source and thins with height,
    # which is what keeps the upper left of the frame calm enough for icons.
    fan = fan * smoothstep((distance - 0.10) / 0.45) * np.exp(-((distance / ray_reach) ** 2))
    image = over(image, rgb(ray), fan * ray_strength)

    # 4. a whisper of shade in the corners, so the frame has a shape.
    centre = np.hypot((x - aspect / 2) / (aspect / 2), (y - 0.5) / 0.5)
    image = image * (1.0 - vignette * smoothstep((centre - 0.45) / 0.95))[..., None]

    return np.clip(image, 0.0, 1.0)


def _to_png(image: np.ndarray) -> Image.Image:
    """Quantise with an ordered dither, which is what keeps the sky smooth."""
    # A 4x4 Bayer matrix scaled to half a level: below the eye, above the
    # banding. No random noise, so the file is byte-for-byte reproducible.
    bayer = np.array(
        [
            [0, 8, 2, 10],
            [12, 4, 14, 6],
            [3, 11, 1, 9],
            [15, 7, 13, 5],
        ],
        dtype=np.float64,
    )
    threshold = (bayer / 16.0 - 0.5) / 255.0
    tiled = np.tile(threshold, (HEIGHT // 4 + 1, WIDTH // 4 + 1))[:HEIGHT, :WIDTH]
    dithered = np.clip(image + tiled[..., None], 0.0, 1.0)
    return Image.fromarray(np.round(dithered * 255.0).astype(np.uint8), mode="RGB")


# --- DAYBREAK ---------------------------------------------------------------
# Warm white above, palest sage underfoot, a warm sun just off the bottom edge.
# The shafts are the ribs of a glasshouse roof seen from inside, first thing in
# the morning.

DAYBREAK = {
    "sky": "#EFF3E9",
    "horizon": "#FBF6EC",
    "ground": "#CBDAC1",
    "glow": "#F7E2B4",
    "ray": "#94B189",
    "source": (0.78, 1.24),
    "glow_radius": 0.74,
    "glow_strength": 0.82,
    "ray_angles": (-0.88, -0.63, -0.41, -0.22, -0.02, 0.21),
    "ray_width": 0.058,
    "ray_strength": 0.28,
    "ray_reach": 1.15,
    "horizon_at": 0.66,
    "vignette": 0.055,
}

# --- HEARTH -----------------------------------------------------------------
# Cream walls, sand underfoot, one amber fire low and right, and terracotta
# shafts widening away from it across the room.

HEARTH = {
    "sky": "#F3E7D4",
    "horizon": "#FAF1E1",
    "ground": "#DFC29C",
    "glow": "#F4BE6E",
    "ray": "#C0764F",
    "source": (0.76, 1.28),
    "glow_radius": 0.70,
    "glow_strength": 0.88,
    "ray_angles": (-0.82, -0.58, -0.37, -0.17, 0.05, 0.29),
    "ray_width": 0.054,
    "ray_strength": 0.24,
    "ray_reach": 1.10,
    "horizon_at": 0.62,
    "vignette": 0.085,
}

TARGETS: dict[str, tuple[dict, Path]] = {
    "daybreak": (DAYBREAK, Path("themes/daybreak/wallpaper/daybreak-first-light.png")),
    "hearth": (HEARTH, Path("themes/hearth/wallpaper/hearth-firelight.png")),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "which",
        nargs="?",
        choices=sorted(TARGETS),
        help="draw only one of them (default: both)",
    )
    args = parser.parse_args(argv)

    wanted = [args.which] if args.which else sorted(TARGETS)
    for name in wanted:
        recipe, relative = TARGETS[name]
        out = REPO_ROOT / relative
        out.parent.mkdir(parents=True, exist_ok=True)
        _to_png(_draw(**recipe)).save(out, format="PNG", optimize=True)
        print(f"wrote {relative} ({out.stat().st_size // 1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
