"""Update checking, and where an update is allowed to be put.

The staging rule is the load-bearing one: an update never lands on top of the
running add-on's folder, because the desktop has already imported that code.
Every path in this file writes into a temporary folder handed in by the test.
"""

from __future__ import annotations

import io
import json
import zipfile

import pytest
from ego_fakes import (
    FakeRunner,
    FakeShellProxy,
    RecordedTransport,
    collect,
    network_error,
)

from gtheme.ego.client import EgoClient
from gtheme.ego.shelldbus import ShellExtensions
from gtheme.ego.updates import (
    COPY,
    UpdateCandidate,
    UpdateChecker,
    UpdateVerdict,
    extension_updates_dir,
    stage_update,
)
from gtheme.ui import jargon


def info(uuid: str, version: float = 60.0, **overrides) -> dict:
    payload = {
        "uuid": uuid,
        "name": uuid.split("@")[0],
        "state": 1.0,
        "type": 2.0,
        "version": version,
        "_generated": "Generated by SweetTooth, do not edit",
    }
    payload.update(overrides)
    return payload


def package(uuid: str, *, with_schemas: bool = True, extra: dict | None = None) -> bytes:
    """A flat package shaped exactly like the ones the library serves."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("metadata.json", json.dumps({"uuid": uuid, "version": 73}))
        archive.writestr("extension.js", "// hello")
        if with_schemas:
            archive.writestr(f"schemas/org.gnome.shell.extensions.{uuid}.gschema.xml", "<schemalist/>")
        for name, body in (extra or {}).items():
            archive.writestr(name, body)
    return buffer.getvalue()


def build(extensions=None, routes=None):
    proxy = FakeShellProxy(extensions or {})
    shell = ShellExtensions(proxy)
    shell.load()
    client = EgoClient(RecordedTransport(routes or {}), "50.4")
    checker = UpdateChecker(client, shell)
    checker.runner = FakeRunner()
    return checker, proxy, shell


# -- the check -------------------------------------------------------------


def test_the_check_asks_about_every_library_packaged_add_on_at_once():
    checker, _proxy, _ = build(
        {"blur-my-shell@aunetx": info("blur-my-shell@aunetx", 60.0)},
        routes={"/update-info/": "update-info.json"},
    )
    box: list = []
    checker.check(collect(box))
    candidates, error = box[0]
    assert error is None
    assert [c.uuid for c in candidates] == ["blur-my-shell@aunetx"]
    assert candidates[0].verdict is UpdateVerdict.UPGRADE
    assert candidates[0].installed_version == 60


def test_a_withdrawn_add_on_is_not_an_update():
    checker, _proxy, _ = build(
        {
            "blur-my-shell@aunetx": info("blur-my-shell@aunetx", 60.0),
            "adb_bp@gnome_extensions.github.com": info("adb_bp@gnome_extensions.github.com", 1.0),
        },
        routes={"/update-info/": "update-info.json"},
    )
    box: list = []
    checker.check(collect(box))
    candidates, _ = box[0]
    withdrawn = next(c for c in candidates if c.uuid.startswith("adb_bp"))
    assert withdrawn.verdict is UpdateVerdict.WITHDRAWN
    assert withdrawn.verdict.is_update is False


def test_add_ons_built_from_source_are_left_out_of_the_comparison():
    """Their version numbers mean something else; comparing them invents news."""
    checker, _proxy, _ = build(
        {"source@x": info("source@x", 3.0, _generated=None)},
        routes={"/update-info/": "update-info.json"},
    )
    box: list = []
    checker.check(collect(box))
    assert box[0] == ([], None)


def test_nothing_installed_means_no_request_and_an_empty_answer():
    checker, _proxy, _ = build({}, routes={})
    box: list = []
    checker.check(collect(box))
    assert box[0] == ([], None)


def test_a_failed_check_reaches_the_caller_as_a_failure():
    checker, _proxy, _ = build(
        {"a@b": info("a@b")}, routes={"/update-info/": network_error()}
    )
    box: list = []
    checker.check(collect(box))
    candidates, error = box[0]
    assert candidates is None and error is not None


# -- resolving one candidate ----------------------------------------------


def test_resolving_fills_in_the_exact_release_to_download():
    checker, _proxy, _ = build(
        {"blur-my-shell@aunetx": info("blur-my-shell@aunetx", 60.0)},
        routes={"/extension-info/": "info-blur-my-shell.json"},
    )
    candidate = UpdateCandidate("blur-my-shell@aunetx", 60, UpdateVerdict.UPGRADE)
    box: list = []
    checker.resolve(candidate, collect(box))
    resolved, error = box[0]
    assert error is None
    assert (resolved.available_version, resolved.version_tag) == (72, 69740)
    assert resolved.ready_to_download is True


def test_an_add_on_with_no_build_for_this_desktop_is_reported_as_withdrawn():
    checker, _proxy, _ = build(
        {"adb_bp@gnome_extensions.github.com": info("adb_bp@gnome_extensions.github.com", 1.0)},
        routes={"/extension-info/": "info-adb-bp-incompatible.json"},
    )
    candidate = UpdateCandidate("adb_bp@gnome_extensions.github.com", 1, UpdateVerdict.UPGRADE)
    box: list = []
    checker.resolve(candidate, collect(box))
    resolved, error = box[0]
    assert error is None
    assert resolved.verdict is UpdateVerdict.WITHDRAWN
    assert resolved.ready_to_download is False


def test_an_unresolved_candidate_cannot_be_downloaded():
    checker, _proxy, _ = build({}, routes={})
    box: list = []
    checker.download_and_stage(
        UpdateCandidate("a@b", 1, UpdateVerdict.UPGRADE), collect(box)
    )
    path, error = box[0]
    assert path is None and isinstance(error, ValueError)


# -- staging ---------------------------------------------------------------


def test_an_update_is_staged_beside_the_running_add_on_and_never_over_it(tmp_path):
    live = tmp_path / "extensions" / "a@b"
    live.mkdir(parents=True)
    (live / "extension.js").write_text("// the code that is currently loaded")
    staged = stage_update("a@b", package("a@b"), directory=tmp_path / "updates", runner=FakeRunner())
    assert staged == tmp_path / "updates" / "a@b"
    assert (staged / "extension.js").read_text() == "// hello"
    assert (live / "extension.js").read_text() == "// the code that is currently loaded"


def test_the_settings_descriptions_are_compiled_where_the_package_left_them_raw(tmp_path):
    runner = FakeRunner()
    staged = stage_update("a@b", package("a@b"), directory=tmp_path, runner=runner)
    assert len(runner.calls) == 1
    argv = runner.calls[0]
    assert argv[:2] == ["glib-compile-schemas", "--strict"]
    # Compiled in the holding folder, before the move — so a failure half way
    # through never leaves a partly-built add-on where a whole one is expected.
    assert argv[2].endswith("/schemas")
    assert argv[2].startswith(str(tmp_path))
    assert (staged / "schemas").is_dir()


def test_a_package_with_no_settings_needs_nothing_compiled(tmp_path):
    runner = FakeRunner()
    stage_update("a@b", package("a@b", with_schemas=False), directory=tmp_path, runner=runner)
    assert runner.calls == []


def test_staging_twice_replaces_what_was_staged_before(tmp_path):
    stage_update("a@b", package("a@b", extra={"old.js": "1"}), directory=tmp_path, runner=FakeRunner())
    staged = stage_update("a@b", package("a@b"), directory=tmp_path, runner=FakeRunner())
    assert not (staged / "old.js").exists()


def test_a_package_that_says_it_is_something_else_is_refused(tmp_path):
    with pytest.raises(ValueError, match="not"):
        stage_update("a@b", package("someone-else@x"), directory=tmp_path, runner=FakeRunner())
    assert list(tmp_path.iterdir()) == []


def test_a_package_that_would_unpack_outside_its_folder_is_refused(tmp_path):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("metadata.json", json.dumps({"uuid": "a@b"}))
        archive.writestr("../../escaped.txt", "gotcha")
    with pytest.raises(ValueError, match="unsafe"):
        stage_update("a@b", buffer.getvalue(), directory=tmp_path, runner=FakeRunner())
    assert not (tmp_path.parent / "escaped.txt").exists()


def test_a_package_with_no_description_in_it_is_refused(tmp_path):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("extension.js", "// nothing else")
    with pytest.raises(ValueError):
        stage_update("a@b", buffer.getvalue(), directory=tmp_path, runner=FakeRunner())


def test_something_that_is_not_a_package_at_all_is_refused(tmp_path):
    with pytest.raises(ValueError):
        stage_update("a@b", b"<html>sorry</html>", directory=tmp_path, runner=FakeRunner())


def test_the_staging_folder_is_the_one_the_desktop_looks_in(tmp_path, monkeypatch):
    monkeypatch.delenv("GTHEME_EXTENSION_UPDATES_DIR", raising=False)
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    assert extension_updates_dir() == tmp_path / "data" / "gnome-shell" / "extension-updates"
    monkeypatch.setenv("GTHEME_EXTENSION_UPDATES_DIR", str(tmp_path / "elsewhere"))
    assert extension_updates_dir() == tmp_path / "elsewhere"


def test_download_and_stage_puts_a_real_package_in_place(tmp_path):
    checker, _proxy, _ = build(
        {"a@b": info("a@b")}, routes={"/download-extension/": package("a@b")}
    )
    candidate = UpdateCandidate("a@b", 60, UpdateVerdict.UPGRADE, available_version=73, version_tag=9)
    box: list = []
    checker.download_and_stage(candidate, collect(box), directory=tmp_path)
    staged, error = box[0]
    assert error is None
    assert (staged / "metadata.json").exists()


# -- the words -------------------------------------------------------------


def test_the_only_promise_made_after_staging_mentions_logging_in_again():
    assert "log in" in COPY["staged"]


def test_nothing_this_module_says_uses_a_word_the_reader_would_have_to_look_up():
    for key, sentence in COPY.items():
        assert jargon.check(sentence, where=key) == []
