"""What the running desktop says about add-ons, and how it is read.

The desktop is replaced by :class:`FakeShellProxy`, which implements the same
abstract class the real proxy does — so everything under test here is the code
that runs against a live session, minus the bus.
"""

from __future__ import annotations

from ego_fakes import FakeShellProxy

from gtheme.ego.shelldbus import (
    EnableResult,
    ExtensionState,
    ExtensionType,
    InstalledExtension,
    ShellError,
    ShellErrorKind,
    ShellExtensions,
    StateWatcher,
    UninstallResult,
)


def info(uuid: str, **overrides) -> dict:
    payload = {
        "uuid": uuid,
        "name": uuid.split("@")[0],
        "state": 1.0,
        "type": 2.0,
        "version": 72.0,
        "hasPrefs": True,
        "enabled": True,
        "_generated": "Generated by SweetTooth, do not edit",
    }
    payload.update(overrides)
    return payload


def shell(**extensions) -> tuple[ShellExtensions, FakeShellProxy]:
    proxy = FakeShellProxy(dict(extensions))
    service = ShellExtensions(proxy)
    service.load()
    return service, proxy


# -- reading the vardict ---------------------------------------------------


def test_numbers_arrive_as_doubles_and_are_cast_once_on_the_way_in():
    parsed = InstalledExtension.from_info("a@b", info("a@b", state=1.0, version=72.0, type=2.0))
    assert parsed.state is ExtensionState.ACTIVE
    assert parsed.type is ExtensionType.PER_USER
    assert parsed.version == 72
    assert parsed.display_version == "72", "a version shown as 72.0 is a bug a user can see"


def test_an_empty_answer_means_the_desktop_has_never_scanned_it():
    """Not uninstalled, not an error — unknown, which is a different sentence."""
    assert InstalledExtension.from_info("ghost@nowhere", {}) is None


def test_an_unrecognised_state_number_does_not_crash_the_parse():
    parsed = InstalledExtension.from_info("a@b", info("a@b", state=42.0))
    assert parsed is not None
    assert parsed.state is None


def test_a_name_shaped_version_is_what_gets_shown():
    parsed = InstalledExtension.from_info(
        "a@b", info("a@b", **{"version-name": "24.1", "version": 24.0})
    )
    assert parsed.display_version == "24.1"
    assert parsed.version == 24


def test_the_library_marker_is_what_separates_packaged_from_home_built():
    packaged = InstalledExtension.from_info("a@b", info("a@b"))
    from_source = InstalledExtension.from_info("c@d", info("c@d", _generated=None))
    assert packaged.from_library is True
    assert from_source.from_library is False


# -- the live list ---------------------------------------------------------


def test_load_reads_everything_once():
    service, proxy = shell(**{"a@b": info("a@b"), "c@d": info("c@d", state=2.0)})
    assert set(service.all) == {"a@b", "c@d"}
    assert [e.uuid for e in service.running()] == ["a@b"]
    assert len(proxy.handlers) == 1, "loading subscribes exactly once"


def test_state_changes_arrive_by_signal_and_are_never_polled():
    service, proxy = shell(**{"a@b": info("a@b", state=2.0)})
    seen: list = []
    service.connect(seen.append)
    proxy.emit_state("a@b", info("a@b", state=1.0))
    assert service.get("a@b").state is ExtensionState.ACTIVE
    assert [e.uuid for e in seen] == ["a@b"]


def test_an_add_on_that_reports_itself_removed_leaves_the_list():
    service, proxy = shell(**{"a@b": info("a@b")})
    proxy.emit_state("a@b", info("a@b", state=99.0))
    assert "a@b" not in service.all


def test_an_add_on_that_appears_at_runtime_joins_the_list():
    service, proxy = shell()
    proxy.arrive("new@thing")
    assert service.knows("new@thing")


def test_knows_asks_the_desktop_when_the_list_has_not_heard_of_it():
    service, proxy = shell()
    proxy.extensions["late@arrival"] = info("late@arrival")
    assert service.knows("late@arrival") is True
    assert service.knows("never@here") is False


def test_only_library_packaged_add_ons_are_offered_for_the_update_check():
    service, _ = shell(
        **{
            "packaged@x": info("packaged@x", version=5.0),
            "source@y": info("source@y", _generated=None, version=3.0),
            "nover@z": info("nover@z", version=None),
        }
    )
    assert service.from_library() == {"packaged@x": 5}


# -- switching on and off --------------------------------------------------


def test_switching_on_an_add_on_the_desktop_knows_works_now():
    service, proxy = shell(**{"a@b": info("a@b", state=2.0, enabled=False)})
    assert service.enable("a@b") is EnableResult.ENABLED_NOW
    assert proxy.enable_calls == ["a@b"]


def test_switching_on_an_unscanned_add_on_is_the_log_out_case_not_a_failure():
    """The desktop answers False; that answer means "next log-in", not "error"."""
    service, proxy = shell()
    assert service.enable("ghost@nowhere") is EnableResult.NEEDS_RELOGIN
    assert proxy.enable_calls == [], "there is no point calling for an add-on it cannot see"


def test_a_refusal_from_a_known_add_on_is_a_real_failure():
    class Stubborn(FakeShellProxy):
        def enable_extension(self, uuid: str) -> bool:
            super().enable_extension(uuid)
            return False

    proxy = Stubborn({"a@b": info("a@b", state=2.0)})
    service = ShellExtensions(proxy)
    service.load()
    assert service.enable("a@b") is EnableResult.FAILED


def test_switching_off_goes_straight_through():
    service, proxy = shell(**{"a@b": info("a@b")})
    assert service.disable("a@b") is True
    assert proxy.disable_calls == ["a@b"]


# -- removal ---------------------------------------------------------------


def test_removing_a_per_user_add_on_works():
    service, proxy = shell(**{"a@b": info("a@b")})
    assert service.uninstall("a@b") is UninstallResult.REMOVED
    assert proxy.uninstall_calls == ["a@b"]
    assert "a@b" not in service.all


def test_a_machine_wide_add_on_gets_its_own_explanation():
    """The desktop returns a bare False for two very different situations."""
    service, proxy = shell(**{"sys@x": info("sys@x", type=1.0)})
    assert service.uninstall("sys@x") is UninstallResult.SYSTEM_WIDE
    assert proxy.uninstall_calls == [], "gtheme does not ask for something it knows is refused"


def test_removing_something_the_desktop_never_heard_of_says_so():
    service, _ = shell()
    assert service.uninstall("ghost@nowhere") is UninstallResult.NOT_KNOWN


# -- errors ----------------------------------------------------------------


def test_error_names_map_onto_the_closed_set_and_never_onto_message_text():
    cases = {
        "org.gnome.Shell.Extensions.Error.NotAllowed": ShellErrorKind.NOT_ALLOWED,
        "org.gnome.Shell.Extensions.Error.DownloadFailed": ShellErrorKind.DOWNLOAD_FAILED,
        "org.gnome.Shell.Extensions.Error.InfoDownloadFailed": ShellErrorKind.DOWNLOAD_FAILED,
        "org.gnome.Shell.Extensions.Error.ExtractFailed": ShellErrorKind.EXTRACT_FAILED,
        "org.gnome.Shell.Extensions.Error.EnableFailed": ShellErrorKind.ENABLE_FAILED,
        "org.freedesktop.DBus.Error.NoReply": ShellErrorKind.NO_REPLY,
        "org.freedesktop.DBus.Error.ServiceUnknown": ShellErrorKind.UNAVAILABLE,
        "com.example.Whatever": ShellErrorKind.OTHER,
    }
    for name, kind in cases.items():
        assert ShellError.from_dbus_name(name, "boom").kind is kind


# -- the pre-armed watcher -------------------------------------------------


def test_the_watcher_only_hears_about_its_own_add_on():
    service, proxy = shell()
    watcher = StateWatcher(uuid="mine@x", shell=service)
    watcher.arm()
    proxy.emit_state("someone-else@y", info("someone-else@y"))
    assert watcher.seen == []
    proxy.emit_state("mine@x", info("mine@x", state=8.0))
    proxy.emit_state("mine@x", info("mine@x", state=1.0))
    assert watcher.seen == [ExtensionState.ACTIVATING, ExtensionState.ACTIVE]
    assert watcher.became_active is True


def test_disarming_stops_the_watcher():
    service, proxy = shell()
    watcher = StateWatcher(uuid="mine@x", shell=service)
    watcher.arm()
    watcher.disarm()
    proxy.emit_state("mine@x", info("mine@x"))
    assert watcher.seen == []
